name: Unit Tests & Deploy
on: [push,workflow_dispatch] # Runs whenver a commit is pushed & allow manually dispatch too
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3 # using officially available action by github. Always lock the version to avoid compatibility issues.
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # npm install
      - name: Run Tests
        run: npm test
  
  deploy:
    needs: tests # If needs multiple jobs than can use [] E.g. [tests, job2, job3...]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3 # using officially available action by github. Always lock the version to avoid compatibility issues.
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # npm install
      - name: Build Project
        run: npm run build
      - name: Deploy the artifact
        run: echo "Deploying ...."